In [1]:
import pandas as pd

df_custom = pd.DataFrame({
    'Company': ['A', 'B', 'C', 'D'],
    'Valuation': [10, 25, 15, 50],
    'Industry': ['Fintech', 'Health', 'Cyber', 'AI'],
    'Year': [2015, 2018, 2012, 2020]
})
df_custom

  Company  Valuation Industry  Year
0       A         10  Fintech  2015
1       B         25   Health  2018
2       C         15    Cyber  2012
3       D         50       AI  2020

In [8]:
df = pd.read_csv('Unicorn_Companies.csv')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1037 entries, 0 to 1036
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            1037 non-null   str
 1   Valuation ($B)     1037 non-null   str
 2   Date Joined        1037 non-null   str
 3   Country            1037 non-null   str
 4   City               1037 non-null   str
 5   Industry           1037 non-null   str
 6   Select Inverstors  1020 non-null   str
 7   Founded Year       994 non-null    float64
 8   Total Raised       1013 non-null   str
 9   Financial Stage    49 non-null     str
 10  Investors Count    1036 non-null   float64
 11  Deal Terms         1008 non-null   float64
 12  Portfolio Exits    49 non-null     float64
dtypes: float64(4), str(9)
memory usage: 68.9 KB

In [10]:
df.describe()

       Founded Year  Investors Count   Deal Terms  Portfolio Exits
count    994.000000      1036.000000  1008.000000        49.000000
mean    2012.710262        14.432432     3.093254         1.346939
std        5.942876         9.946537     2.159764         0.751416
min     1919.000000         1.000000     1.000000         1.000000
25%     2011.000000         8.000000     1.000000         1.000000
50%     2014.000000        13.000000     3.000000         1.000000
75%     2016.000000        19.000000     4.000000         1.000000
max     2021.000000        91.000000    19.000000         5.000000

In [11]:
df.columns

Index(['Company', 'Valuation ($B)', 'Date Joined', 'Country', 'City',
       'Industry', 'Select Inverstors', 'Founded Year', 'Total Raised',
       'Financial Stage', 'Investors Count', 'Deal Terms', 'Portfolio Exits'],
      dtype='str')

In [12]:
df.head()

,Company,Valuation ($B),Date Joined,Country,City,Industry,Select Inverstors,Founded Year,Total Raised,Financial Stage,Investors Count,Deal Terms,Portfolio Exits
0,Bytedance,$140,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S...",2012.0,$7.44B,IPO,28.0,8.0,5.0
1,SpaceX,$100.3,12/1/2012,United States,Hawthorne,Other,"Founders Fund, Draper Fisher Jurvetson, Rothen...",2002.0,$6.874B,NaN,29.0,12.0,NaN
2,Stripe,$95,1/23/2014,United States,San Francisco,Fintech,"Khosla Ventures, LowercaseCapital, capitalG",2010.0,$2.901B,Asset,39.0,12.0,1.0
3,Klarna,$45.6,12/12/2011,Sweden,Stockholm,Fintech,"Institutional Venture Partners, Sequoia Capita...",2005.0,$3.472B,Acquired,56.0,13.0,1.0
4,Epic Games,$42,10/26/2018,United States,Cary,Other,"Tencent Holdings, KKR, Smash Ventures",1991.0,$4.377B,Acquired,25.0,5.0,2.0

In [15]:
df[['Company', 'Valuation ($B)', 'Industry']]

           Company Valuation ($B)                      Industry
0        Bytedance           $140       Artificial intelligence
1           SpaceX         $100.3                         Other
2           Stripe            $95                       Fintech
3           Klarna          $45.6                       Fintech
4       Epic Games            $42                         Other
...            ...            ...                           ...
1032     Timescale             $1  Internet software & services
1033      Scalapay             $1                       Fintech
1034  Omada Health             $1                        Health
1035    BlueVoyant             $1                 Cybersecurity
1036          Veev             $1  Internet software & services

[1037 rows x 3 columns]

In [18]:
df[df['Founded Year'] > 2018]

,Company,Valuation ($B),Date Joined,Country,City,Industry,Select Inverstors,Founded Year,Total Raised,Financial Stage,Investors Count,Deal Terms,Portfolio Exits
70,Ramp,$8,3/29/2021,United States,New York,Fintech,"D1 Capital Partners, Stripe, Coatue Management",2019.0,$827M,NaN,18.0,5.0,NaN
99,Black Unicorn Factory,$6.1,5/20/2021,United States,Los Angeles,Other,Barter Ventures,2020.0,$645M,NaN,1.0,1.0,NaN
103,Wiz,$6,3/17/2021,Israel,Tel Aviv,Cybersecurity,"Insight Partners, Sequoia Capital, Index Ventures",2020.0,$600M,NaN,10.0,4.0,NaN
140,Ola Electric Mobility,$5,7/2/2019,India,Bengaluru,Auto & transportation,"SoftBank Group, Tiger Global Management, Matri...",2019.0,$822.29M,NaN,20.0,3.0,NaN
144,Cerebral,$4.8,6/10/2021,United States,San Francisco,Health,"Oak HC/FT Partners, Artis Ventures, WestCap Group",2020.0,NaN,NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,Cadence,$1,12/14/2021,United States,New York,Health,"Thrive Capital, General Catalyst, Coatue Manag...",2020.0,$141M,NaN,8.0,1.0,NaN
1008,Noname Security,$1,12/15/2021,United States,Palo Alto,Cybersecurity,"Insight Partners, Lightspeed Venture Partners,...",2020.0,$220M,NaN,7.0,1.0,NaN
1011,Haomao.AI,$1,12/22/2021,China,Beijing,Artificial Intelligence,"Qualcomm Ventures, Nine Intelligence Capital, ...",2019.0,$203.91M,NaN,7.0,1.0,NaN
1029,Axelar,$1,2/15/2022,Canada,Waterloo,Internet software & services,"Lemniscap VC, North Island Ventures, Polychain...",2020.0,$63.75M,NaN,26.0,1.0,NaN
1033,Scalapay,$1,2/23/2022,Italy,Milan,Fintech,"Fasanara Capital, Tiger Global Management, Bal...",2019.0,$700M,NaN,10.0,2.0,NaN