In [2]:
import pandas as pd
import numpy as np

завантажуємо потрібні біліотеки для подальшої роботи з даними

In [3]:
df = pd.read_csv('Unicorn_Companies.csv')

тепер основне - завантажуємо датасет.
мій датасет про компанії - єдинороги (стартапи , з оціночними вартостями більше 1млрд доларів США). отже, далі після наших запитів ми розглянемо детальніше структуру датасету. за допомогою нього ми зможемо дізнатися про те, з яких регіонів стартапи (в подальшому зможемо ставити питання чи географічне положення впливає на це), які галузі є найприбутковішими (які менеше), скільки часу потребує компанія для того, щоб вирости до рівня 1 млрд доларів США. також зможемо дізнатися , хто фінансує ці стартапи.

In [4]:
df.shape

(1037, 13)

на цьому кроці бачимо масштаб даних: 1037 компаній (рядків) та 13 параметрів (стовпчиків).

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1037 entries, 0 to 1036
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            1037 non-null   str
 1   Valuation ($B)     1037 non-null   str
 2   Date Joined        1037 non-null   str
 3   Country            1037 non-null   str
 4   City               1037 non-null   str
 5   Industry           1037 non-null   str
 6   Select Inverstors  1020 non-null   str
 7   Founded Year       994 non-null    float64
 8   Total Raised       1013 non-null   str
 9   Financial Stage    49 non-null     str
 10  Investors Count    1036 non-null   float64
 11  Deal Terms         1008 non-null   float64
 12  Portfolio Exits    49 non-null     float64
dtypes: float64(4), str(9)
memory usage: 68.9 KB

за допомогою цього запиту, бачимо структуру наших даних. Вже можемо проаналізувати чи є порожні (нульові) значення, чи відповідає тип данних нашим самим данним. Отже,бачимо присутні або str ( текстові) данні або float 64 (кількісні), тепер їх зіставляємо з типом данних: начебто проблем не знайшли, адже еткстові зіставляються з данними назв компаній, країн, тощо , а кількісні із числовими значеннями. інколи, в цьому пункті можна одразу зрозуміти чи стовпчики з датою мають правильний тип і якщо ні, то одразу замінити на тип дати, щоб далі легше проводити аналітику. одразу бачимо де нульові значення , шляхом порівнння кількості всіх : 1037 із зазначенними кількрстями у звіті.

In [6]:
df.describe()

       Founded Year  Investors Count   Deal Terms  Portfolio Exits
count    994.000000      1036.000000  1008.000000        49.000000
mean    2012.710262        14.432432     3.093254         1.346939
std        5.942876         9.946537     2.159764         0.751416
min     1919.000000         1.000000     1.000000         1.000000
25%     2011.000000         8.000000     1.000000         1.000000
50%     2014.000000        13.000000     3.000000         1.000000
75%     2016.000000        19.000000     4.000000         1.000000
max     2021.000000        91.000000    19.000000         5.000000

тепер цей запит нам показує загальну статистику (розраховую звісно ж лише для кількісних колонок): середній рік заснування компаній, середню кількість інвесторів на один стартап,умови угод та виходи з портфеля. далі бачимо, що є рядки: кількості ненульових значень, середнього значення (орієнтовно 2013 рік у році заснування компаній), середня кількість інвесторів= 14, але наприклад із максимальним порогом в 91 інвестора на одну компанію! далі бачимо стандартне відхилення, тобто , наприклад для року заснування 5.9, що означає , що більшість компаній створені +- за останні 6 років від середнього). далоі бачимо стовпчики для найменшого та найбільшого значення в категоріях. 25% перший квартиль , тобто більшість компаній мають значення менше або рівне цьому: 25% компаній засновані у 2011-му році та мають приблизно 8 інвесторів. 50% медіана, центральне значення:медіанний рік заснування 2014, кількість інвесторів - 13. 75% третій квартиль, 75% компаній мають значення менше за це: 75% компаній мають до 19 інвесторів.

In [7]:
df.describe(include='all')

,Company,Valuation ($B),Date Joined,Country,City,Industry,Select Inverstors,Founded Year,Total Raised,Financial Stage,Investors Count,Deal Terms,Portfolio Exits
count,1037,1037,1037,1037,1037,1037,1020,994.000000,1013,49,1036.000000,1008.000000,49.000000
unique,1035,200,623,46,256,33,1005,NaN,913,9,NaN,NaN,NaN
top,Bolt,$1,7/13/2021,United States,San Francisco,Fintech,Sequoia Capital,NaN,$300M,Acquired,NaN,NaN,NaN
freq,2,244,9,536,145,205,3,NaN,9,22,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012.710262,NaN,NaN,14.432432,3.093254,1.346939
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.942876,NaN,NaN,9.946537,2.159764,0.751416
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1919.000000,NaN,NaN,1.000000,1.000000,1.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011.000000,NaN,NaN,8.000000,1.000000,1.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.000000,NaN,NaN,13.000000,3.000000,1.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.000000,NaN,NaN,19.000000,4.000000,1.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,91.000000,19.000000,5.000000

тепер включаємо абсолютно всі значення, тобто із текстовими. можемо побачити скільки унікальних країн, індустрій або цінників вартості . тепер відслідковуємо топ-значення, тобто ті, що зустрічаються найчастіше: найпопулярніша країна США, галузь - фінансові технології, найпопулярніший фонд та найпопулярнішу орцінку капіталізації. далі у наступному стовпчику бачимо наскільке часто наше топ-значення зустрічається.

In [8]:
df.columns

Index(['Company', 'Valuation ($B)', 'Date Joined', 'Country', 'City',
       'Industry', 'Select Inverstors', 'Founded Year', 'Total Raised',
       'Financial Stage', 'Investors Count', 'Deal Terms', 'Portfolio Exits'],
      dtype='str')

бачимо зведення щодо наших колонок, тобто наші компанії розглядаються через ці характеритсики:

In [9]:
df.head()

,Company,Valuation ($B),Date Joined,Country,City,Industry,Select Inverstors,Founded Year,Total Raised,Financial Stage,Investors Count,Deal Terms,Portfolio Exits
0,Bytedance,$140,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S...",2012.0,$7.44B,IPO,28.0,8.0,5.0
1,SpaceX,$100.3,12/1/2012,United States,Hawthorne,Other,"Founders Fund, Draper Fisher Jurvetson, Rothen...",2002.0,$6.874B,NaN,29.0,12.0,NaN
2,Stripe,$95,1/23/2014,United States,San Francisco,Fintech,"Khosla Ventures, LowercaseCapital, capitalG",2010.0,$2.901B,Asset,39.0,12.0,1.0
3,Klarna,$45.6,12/12/2011,Sweden,Stockholm,Fintech,"Institutional Venture Partners, Sequoia Capita...",2005.0,$3.472B,Acquired,56.0,13.0,1.0
4,Epic Games,$42,10/26/2018,United States,Cary,Other,"Tencent Holdings, KKR, Smash Ventures",1991.0,$4.377B,Acquired,25.0,5.0,2.0

цей запит допомагає коротко ознайомитися із таблицею, виводить за замовчуванням 5 перших рядків таблиці.

In [16]:
y = df['Valuation ($B)']                
X = df.drop(columns=['Valuation ($B)'])

виділяємо цільову змінну. тобто у - цільова змінна(те, що ми аналізуємо, бажаємо передбачити - підсумкова вартість компанії). х - ознаки (те, що впливає на цю оцінку). в подальшому за допогою цього можна буде робити прогнози моделі, тож видалити нашу цільову змінну важливо, щоб модель сама навчалася.

In [10]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
print("Чисельні стовпці:", num_cols)

Чисельні стовпці: ['Founded Year', 'Investors Count', 'Deal Terms', 'Portfolio Exits']

виідляємо лише ті стовпці, що мають числове значення та записуємо їх у змінну num cols, в подальшому нам це допоможе робити зручніше та трошки швидше аналіз.

In [11]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1032    False
1033    False
1034    False
1035    False
1036    False
Length: 1037, dtype: bool

бачимо через цей запит, що наш дата сет немає дублікатів, тобто кожна компанія записана лише один раз, тому для наочності додамо штучний дублікат.

In [20]:
df = pd.concat([df, df.iloc[:2]], ignore_index=True)

функція контакт, копіює два перщих рядки та ігноруючи номерацію додає їх в кінець нашої таблиці.

In [12]:
print("Shape до видалення дублікатів:", df.shape)
print("Кількість дублікатів:", df.duplicated().sum())

Shape до видалення дублікатів: (1037, 13)
Кількість дублікатів: 0

маємо тепер перевірити розмірність нашої таблиці: на правду стало на два рядки більше 1039 (було 1037) та підраховуючи кількість дублікатів, впенюємося, шо маємо два.

In [23]:
df = df.drop_duplicates()
print("Shape після видалення дублікатів:", df.shape)

Shape після видалення дублікатів: (1037, 13)

тепер за допомогою цієї функції видаляємо дублікати та перевіряємо знову розмірність датасету чи вона така , як першочергова? - так! все чудово!

In [24]:
print("\nShape до видалення порожніх значень:", df.shape)
print("Порожні значення в стовпцях:\n", df.isna().sum())

Shape до видалення порожніх значень: (1037, 13)
Порожні значення в стовпцях:
 Company                0
Valuation ($B)         0
Date Joined            0
Country                0
City                   0
Industry               0
Select Inverstors     17
Founded Year          43
Total Raised          24
Financial Stage      988
Investors Count        1
Deal Terms            29
Portfolio Exits      988
dtype: int64

розмврнвсть до видалення порожніх значень. наступна функція рахує де і скільки пропущених значень. де 0 - означає, що стовпець повністю заповнений.

In [25]:
df_clean = df.dropna()
print("Shape після видалення порожніх значень:", df_clean.shape)

Shape після видалення порожніх значень: (46, 13)

ця функція видаляє пропущенні значення, бачимо, як відчутно зменшився датасет.вона видаляє всі рядки , де є хоча б один пропуск

In [13]:
df['Country'].value_counts().head(5)

Country
United States     536
China             168
India              63
United Kingdom     42
Germany            24
Name: count, dtype: int64

робимо легкий запит для подальшого висновку: оцінюємо топ 5 країн за кількістю компаній.

In [14]:
df['Industry'].value_counts().head(5)

Industry
Fintech                            205
Internet software & services       192
E-commerce & direct-to-consumer    107
Artificial intelligence             71
Health                              69
Name: count, dtype: int64

топ 5 галузей :

In [19]:
df[['Company', 'Valuation ($B)', 'Country', 'Investors Count']].sort_values(by='Investors Count', ascending=False).head(3)

         Company Valuation ($B)         Country  Investors Count
765       Turing           $1.1   United States             91.0
74         Hopin          $7.75  United Kingdom             85.0
73   Dapper Labs           $7.6          Canada             85.0

топ три компанії , що зібрали найбільшу кількість інвесторів.

висновок: початковий датасет містив 1037 компаній, рядків та 13 стовпчиків , тобто ознак, за якими ми їх характеризуємо. побачили, що в нашому оригінальному датасеті не було дублікатів, тож для наочності подальних запитів - додали їх штучно. виявили пропущені значення: ключові характеристики із назвою, країною, галуззю, вартістю заповненні повністю, але інші стопці мали пропущені значення. (доволі багато!). сформулювали "очищений" датасет, де просто прибрали пусті значення, щоб продемонтрувати його розмірність. розділили цільову змінну та її ознаки. 

дізналися, що країна-лідер серед стартапів це США (536 кількість), на другому місці Китай (168 кількість). Найбільше стартапів у сферах фінансових технологіях (205) та програмному сервісі (192). З оцінкою загальної характеристики також дізналися, шо найпоширеніша оцінка стартапів є базовий поріг у 1 млрд доларів сша  (таку вартість мають 244 компанії).