In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('Unicorn_Companies.csv')

In [7]:
df.shape

(1037, 13)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1037 entries, 0 to 1036
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            1037 non-null   str
 1   Valuation ($B)     1037 non-null   str
 2   Date Joined        1037 non-null   str
 3   Country            1037 non-null   str
 4   City               1037 non-null   str
 5   Industry           1037 non-null   str
 6   Select Inverstors  1020 non-null   str
 7   Founded Year       994 non-null    float64
 8   Total Raised       1013 non-null   str
 9   Financial Stage    49 non-null     str
 10  Investors Count    1036 non-null   float64
 11  Deal Terms         1008 non-null   float64
 12  Portfolio Exits    49 non-null     float64
dtypes: float64(4), str(9)
memory usage: 68.9 KB

In [13]:
df.describe()

       Founded Year  Investors Count   Deal Terms  Portfolio Exits
count    994.000000      1036.000000  1008.000000        49.000000
mean    2012.710262        14.432432     3.093254         1.346939
std        5.942876         9.946537     2.159764         0.751416
min     1919.000000         1.000000     1.000000         1.000000
25%     2011.000000         8.000000     1.000000         1.000000
50%     2014.000000        13.000000     3.000000         1.000000
75%     2016.000000        19.000000     4.000000         1.000000
max     2021.000000        91.000000    19.000000         5.000000

In [14]:
df.columns

Index(['Company', 'Valuation ($B)', 'Date Joined', 'Country', 'City',
       'Industry', 'Select Inverstors', 'Founded Year', 'Total Raised',
       'Financial Stage', 'Investors Count', 'Deal Terms', 'Portfolio Exits'],
      dtype='str')

In [15]:
df.head()

,Company,Valuation ($B),Date Joined,Country,City,Industry,Select Inverstors,Founded Year,Total Raised,Financial Stage,Investors Count,Deal Terms,Portfolio Exits
0,Bytedance,$140,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S...",2012.0,$7.44B,IPO,28.0,8.0,5.0
1,SpaceX,$100.3,12/1/2012,United States,Hawthorne,Other,"Founders Fund, Draper Fisher Jurvetson, Rothen...",2002.0,$6.874B,NaN,29.0,12.0,NaN
2,Stripe,$95,1/23/2014,United States,San Francisco,Fintech,"Khosla Ventures, LowercaseCapital, capitalG",2010.0,$2.901B,Asset,39.0,12.0,1.0
3,Klarna,$45.6,12/12/2011,Sweden,Stockholm,Fintech,"Institutional Venture Partners, Sequoia Capita...",2005.0,$3.472B,Acquired,56.0,13.0,1.0
4,Epic Games,$42,10/26/2018,United States,Cary,Other,"Tencent Holdings, KKR, Smash Ventures",1991.0,$4.377B,Acquired,25.0,5.0,2.0

Виділяємо цільову змінну 'Valuation'

In [16]:
y = df['Valuation ($B)']                
X = df.drop(columns=['Valuation ($B)'])     # всі інші стовпці

In [18]:
num_cols = [c for c in df.columns if df[c].dtype in ['int64', 'float64']]

In [19]:
print("Target data, Розмірність:", y.shape)
print("Чисельні стовпці:", num_cols)

Target data, Розмірність: (1037,)
Чисельні стовпці: ['Founded Year', 'Investors Count', 'Deal Terms', 'Portfolio Exits']

додамо штучний дублікат

In [20]:
df = pd.concat([df, df.iloc[:2]], ignore_index=True)

In [21]:
print("Shape до видалення дублікатів:", df.shape)
print("Кількість дублікатів:", df.duplicated().sum())

Shape до видалення дублікатів: (1039, 13)
Кількість дублікатів: 2

In [23]:
df = df.drop_duplicates()
print("Shape після видалення дублікатів:", df.shape)

Shape після видалення дублікатів: (1037, 13)

In [24]:
print("\nShape до видалення порожніх значень:", df.shape)
print("Порожні значення в стовпцях:\n", df.isna().sum())

Shape до видалення порожніх значень: (1037, 13)
Порожні значення в стовпцях:
 Company                0
Valuation ($B)         0
Date Joined            0
Country                0
City                   0
Industry               0
Select Inverstors     17
Founded Year          43
Total Raised          24
Financial Stage      988
Investors Count        1
Deal Terms            29
Portfolio Exits      988
dtype: int64

In [25]:
df_clean = df.dropna()
print("Shape після видалення порожніх значень:", df_clean.shape)

Shape після видалення порожніх значень: (46, 13)